/**
 * @file AddCircle Icon
 * @author Auto Generated by Icons
 */

import { h } from 'vue';
import { IconBuilder } from '../../icon-builder';
import { IconSvgRenderData } from '../../_types/common';

export default IconBuilder('add-circle', (data: IconSvgRenderData) => (
  <svg
    width={data.size}
    height={data.size}
    fill="none"
    class={data.className}
    viewBox="0 0 48 48"
  >
    <path
      fill={data.colorDesc[1]}
      stroke={data.colorDesc[0]}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4 4 12.954 4 24s8.954 20 20 20Z"
    />
    <path
      stroke={data.colorDesc[2]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M24 16v16m-8-8h16"
    />
  </svg>
));
