/**
 * @file ZoomOut Icon
 * @author Auto Generated by Icons
 */

import { h } from 'vue';
import { IconBuilder } from '../../icon-builder';
import { IconSvgRenderData } from '../../_types/common';

export default IconBuilder('zoom-out', (data: IconSvgRenderData) => (
  <svg
    width={data.size}
    height={data.size}
    fill="none"
    class={data.className}
    viewBox="0 0 48 48"
  >
    <path
      fill={data.colorDesc[1]}
      stroke={data.colorDesc[0]}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M21 38c9.389 0 17-7.611 17-17S30.389 4 21 4 4 11.611 4 21s7.611 17 17 17Z"
    />
    <path
      stroke={data.colorDesc[2]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M15 21h12"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="m33.222 33.222 8.485 8.485"
    />
  </svg>
));
