/**
 * @file FriendsCircle Icon
 * @author Auto Generated by Icons
 */

import { h } from 'vue';
import { IconBuilder } from '../../icon-builder';
import { IconSvgRenderData } from '../../_types/common';

export default IconBuilder('friends-circle', (data: IconSvgRenderData) => (
  <svg
    width={data.size}
    height={data.size}
    fill="none"
    class={data.className}
    viewBox="0 0 48 48"
  >
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4 4 12.954 4 24s8.954 20 20 20Z"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="M31 7v17V7Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M31 7v17"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="m16.636 6.636 14.142 14.142L16.636 6.636Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="m16.636 6.636 14.142 14.142"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="M7 17h17H7Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M7 17h17"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="M20.364 17.636 6.222 31.778l14.142-14.142Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M20.364 17.636 6.222 31.778"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="M17 25v17-17Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M17 25v17"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="m17.636 27.636 14.142 14.142-14.142-14.142Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="m17.636 27.636 14.142 14.142"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="M24 31h18-18Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M24 31h18"
    />
    <path
      fill={data.colorDesc[1]}
      fill-rule="evenodd"
      d="M42.364 16.636 28.222 30.778l14.142-14.142Z"
      clip-rule="evenodd"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M42.364 16.636 28.222 30.778"
    />
    <path
      fill={data.colorDesc[1]}
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M24 31a7 7 0 1 0 0-14 7 7 0 0 0 0 14Z"
    />
  </svg>
));
