/**
 * @file TriangleDown Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'triangle-down',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path fill=${data.colorDesc[1]} stroke=${data.colorDesc[0]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M36 19 24 31 12 19h24Z"/></svg>`
);
