/**
 * @file TriangleLeft Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'triangle-left',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path fill=${data.colorDesc[1]} stroke=${data.colorDesc[0]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M30 36 18 24l12-12v24Z"/></svg>`
);
