/**
 * @file Camera Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'camera',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path fill=${data.colorDesc[1]} stroke=${data.colorDesc[0]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="m15 12 3-6h12l3 6H15Z"/><rect width="40" height="30" x="4" y="12" fill=${data.colorDesc[1]} stroke=${data.colorDesc[0]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} rx="3"/><path fill=${data.colorDesc[3]} stroke=${data.colorDesc[2]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M24 35a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z"/></svg>`
);
