/**
 * @file TriangleUp Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'triangle-up',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path fill=${data.colorDesc[1]} stroke=${data.colorDesc[0]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="m12 29 12-12 12 12H12Z"/></svg>`
);
