/**
 * @file ArrowRight Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'arrow-right',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path stroke=${data.colorDesc[0]} stroke-linecap=${data.strokeLineCap} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M42 24H6m24-12 12 12-12 12"/></svg>`
);
