/**
 * @file Copy Icon
 * @author Auto Generated by Icons
 */

import { h } from 'vue';
import { IconBuilder } from '../../icon-builder';
import { IconSvgRenderData } from '../../_types/common';

export default IconBuilder('copy', (data: IconSvgRenderData) => (
  <svg
    width={data.size}
    height={data.size}
    fill="none"
    class={data.className}
    viewBox="0 0 48 48"
  >
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M13 12.432v-4.62A2.813 2.813 0 0 1 15.813 5h24.374A2.813 2.813 0 0 1 43 7.813v24.375A2.813 2.813 0 0 1 40.187 35h-4.67"
    />
    <path
      fill={data.colorDesc[1]}
      stroke={data.colorDesc[0]}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M32.188 13H7.811A2.813 2.813 0 0 0 5 15.813v24.374A2.813 2.813 0 0 0 7.813 43h24.375A2.813 2.813 0 0 0 35 40.187V15.814A2.813 2.813 0 0 0 32.187 13Z"
    />
  </svg>
));
