/**
 * @file ArrowDown Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'arrow-down',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path stroke=${data.colorDesc[0]} stroke-linecap=${data.strokeLineCap} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M24 42V6m12 24L24 42 12 30"/></svg>`
);
