/**
 * @file Code Icon
 * @author Auto Generated by Icons
 */

import { h } from 'vue';
import { IconBuilder } from '../../icon-builder';
import { IconSvgRenderData } from '../../_types/common';

export default IconBuilder('code', (data: IconSvgRenderData) => (
  <svg
    width={data.size}
    height={data.size}
    fill="none"
    class={data.className}
    viewBox="0 0 48 48"
  >
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M16 13 4 25.432 16 37M32 13l12 12.432L32 37"
    />
    <path
      stroke={data.colorDesc[0]}
      stroke-linecap={data.strokeLineCap}
      stroke-width={data.strokeWidth}
      d="m28 4-7 40"
    />
  </svg>
));
