/**
 * @file Application Icon
 * @author Auto Generated by Icons
 */

import { h } from 'vue';
import { IconBuilder } from '../../icon-builder';
import { IconSvgRenderData } from '../../_types/common';

export default IconBuilder('application', (data: IconSvgRenderData) => (
  <svg
    width={data.size}
    height={data.size}
    fill="none"
    class={data.className}
    viewBox="0 0 48 48"
  >
    <path
      fill={data.colorDesc[1]}
      stroke={data.colorDesc[0]}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M41 14 24 4 7 14v20l17 10 17-10V14Z"
    />
    <path
      stroke={data.colorDesc[2]}
      stroke-linecap={data.strokeLineCap}
      stroke-linejoin={data.strokeLineJoin}
      stroke-width={data.strokeWidth}
      d="M16 18.997 23.993 24l8.002-5.003M24 24v9"
    />
  </svg>
));
