/**
 * @file Android Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'android',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path fill=${data.colorDesc[1]} stroke=${data.colorDesc[0]} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M43.901 36H4.1C5.102 25.893 13.629 18 24 18c10.37 0 18.898 7.893 19.901 18Z"/><path stroke=${data.colorDesc[0]} stroke-linecap=${data.strokeLineCap} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="m14 20-4-7m23 7 4-7"/><circle cx="15" cy="29" r="2" fill=${data.colorDesc[2]}/><circle cx="33" cy="29" r="2" fill=${data.colorDesc[2]}/></svg>`
);
