/**
 * @file Up Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'up',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path stroke=${data.colorDesc[0]} stroke-linecap=${data.strokeLineCap} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="m13 30 12-12 12 12"/></svg>`
);
