/**
 * @file ArrowLeft Icon
 * @author Auto Generated by Icons
 */

import { IconBuilder } from '../../icon-builder';

export default IconBuilder(
  'arrow-left',
  (data) =>
    `<svg width=${data.size} height=${data.size} fill="none" class=${data.className} viewBox="0 0 48 48"><path stroke=${data.colorDesc[0]} stroke-linecap=${data.strokeLineCap} stroke-linejoin=${data.strokeLineJoin} stroke-width=${data.strokeWidth} d="M5.799 24h36m-24 12-12-12 12-12"/></svg>`
);
